### ISSUE TITLE
amb v1 要做的事以及当前进度

### ISSUE THREAD

**Issue by sorrycc** [animajs/amb#1]
v1 仅包含项目的生成和构建。
## 项目生成
- [x] 目录完整复制
- [x] 文件内容支持变量替换
- [x] 项目文件夹已存在时的冲突抛错
### Html
- [x] inline
- [x] group
- [x] 相对路径图片上传
- [x] [cdn](https://github.com/afc163/cdn) 封装，添加多图上传、md5 cache、--quiet 参数支持等
### CSS
- [x] less 支持
- [x] @import 合并
- [x] cssmin
- [x] peaches
- [x] 相对路径图片上传
### JavaScript
- [ ] ~~coffee 支持，包含 build 和 spm install 两部分~~
- [x] seajs transport, concat
- [x] seajs mini 版，@army8735 已完成
- [x] 封装成 window.var
- [x] spm install，安装依赖
### img
- [x] imagemin
### 其他
- [x] 通过 package.json -> amb 进行配置 (原子化)
- [x] watch 支持

**Comment by sorrycc** [comment]
cdn 封装完成
- https://github.com/afc163/cdn/pull/12
- https://github.com/animajs/amb/commit/8bd45e0ace2d2880ff9a527d94098092197fd2d6

**Comment by sorrycc** [comment]
相对路径图片上传 完成
- https://github.com/animajs/amb/commit/cef9bf4b4db97456aa7f695d7425cea2bf84ed5e
- https://github.com/animajs/amb/commit/2bd3fd2f261c25bb0bfa659a6a8804f785a0920b

**Comment by sorrycc** [comment]
peaches 完成
- https://github.com/animajs/amb/commit/1097781cb0754e492f7d303a86d690020c1bed34

**Comment by sorrycc** [comment]
相对路径图片上传(CSS) 完成
- https://github.com/animajs/amb/commit/ff98b01563145cde5e15d78a7b168493fc356319
- https://github.com/animajs/amb/commit/8ea4c46e5cb0a0204a635c044505326900e709cc

**Comment by sorrycc** [comment]
`spm install` 完成
- https://github.com/animajs/amb/commit/5fc364e54b759f081799b5cda2ea47bab1827530

spm3-anima fork 自 spm3，spm3 发布后改成依赖 spm3

**Comment by lifesinger** [comment]
赞云谦速度，非常快！

**Comment by sorrycc** [comment]
`imagemin` 完成
- https://github.com/animajs/amb/commit/cc5c8f6f5fc74389fe307e85b4814523a94c5bbf

**Comment by sorrycc** [comment]
`封装成 window.var` 完成
- https://github.com/animajs/amb/commit/b1ea9ba3055ef8beed9207bd83a3e5b58294686d

`$ amb build -s foo` 会生成名为 `foo` 的全局对象，指向入口文件。

**Comment by sorrycc** [comment]
`coffee` 需要 [gulp-transport](https://github.com/popomore/gulp-transport) 支持，暂时做不了，下一个版本再加。

**Comment by sorrycc** [comment]
`通过 package.json -> amb 进行配置 (原子化)` 完成
- https://github.com/animajs/amb/commit/5f2ceb7efb2598245a42d5a849ac02c7b9d0c49a

**Comment by SMbey0nd** [comment]
太赞了，希望能早点开始试用
