### ISSUE TITLE
amb build的几个问题

### ISSUE THREAD

**Issue by SMbey0nd** [animajs/amb#11]
目前不支持.htm后缀文件；
build时默认关闭img上传cdn的设置；
增加img目录的本地build拷贝（离线web app应用）；
output支持通配符，适应文件数量多的情况；
考虑自定义gulp任务的入口；
amb install可同时代理spm install和npm install；
考虑本地、测试、正式环境的切换功能；通过配置切换不同入口。
amb build时，同时增加debug和min两个文件，便于测试。

**Comment by fangk** [comment]
我有一个目标.  git pull 代码源. amb install,   把npm install的事情也做了. 
这样所有的命令就可以使用了

**Comment by sorrycc** [comment]
好建议，我整理 1.3 方案时考虑进去。
1. 目前不支持.htm后缀文件
   bug
2. img 的处理
   路径处理有点麻烦，因为现在支持拍平和不拍平两种打包方式。需要整体考虑下。
3. 通配符
   会支持 glob 语法
4. 考虑自定义gulp任务的入口
   已有方案，1.3 里会支持
5. amb install可同时代理spm install和npm install
   这个暂不考虑
6. 考虑本地、测试、正式环境的切换功能；通过配置切换不同入口
   环境切换可以通过 server + hosts 的方式，另外 api mock 的功能也回考虑进去

**Comment by sorrycc** [comment]
TODO：
- [ ] 目前不支持.htm后缀文件；
- [ ] build时默认关闭img上传cdn的设置；增加img目录的本地build拷贝（离线web app应用）；
- [x] output支持通配符，适应文件数量多的情况；
- [ ] 考虑自定义gulp任务的入口；

**Comment by SMbey0nd** [comment]
amb build时，同时增加debug和min两个文件，便于测试。
目前情况是，amb build会生成debug文件，而build -pubilsh则直接生成min文件会把debug文件覆盖，不能并存。
（已编辑原帖）
