### ISSUE TITLE
对工具强依赖的问题

### ISSUE THREAD

**Issue by SMbey0nd** [animajs/amb#8]
现在有不少同学反馈，目前的开发模式，对工具的依赖太强。
例如，

```
一些很简单的项目不想用工具，直接手工创建个模块，脱离了工具就很难做到；
一个已经发上线的项目，想代理到本地调试的时候，想要代理到src目录里，也会有缺少defined的问题；
本地调试时，如果脱离了amb，也很难去直接做调试。
```

可能这些问题脱离了amb的范畴，属于spm要考虑的事情了~

想讨论看看有没有什么方案，是可以解决这些强依赖的问题，即使脱离了工具，用户仍然能比较容易地完成这些工作。

**Comment by sorrycc** [comment]
1. 确实很简单的项目，比如只需要 jQuery、anima 组件等很通用的库，可以直接 use 已发布到 cdn 上的包来进行开发，和之前的方式一样
2. serve-spm 已经考虑了代理到本地调试的情况，{{name}}/{{version}}/{{relative_path}} 会映射到 {{relative_path}}
3. 还有个 seajs 插件的方式，https://github.com/seajs/seajs-wrap ，能解决基本问题
